---
- name: install 
  hosts: hosts 
  remote_user: vagrant 
  become: yes 
  tasks: 
  
  - name: get update 
    apt: update_cache=yes 

  - name: install curl 
    apt: name=curl state=present
 
  - name: add gpg key
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
 
  - name: add docker repo 
    shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

  - name: update node 
    apt: update_cache=yes 

  - name: install docker repo 
    shell: "apt-cache policy docker-ce"

  - name: install docker 
    apt: name=docker-ce state=present 

  - name: install pip
    easy_install: name=pip state=present

  - name: install docker-py 
    pip: name=docker-py state=present

  - name: install yum 
    apt: name=yum state=present

  - name: get update 
    apt: update_cache=yes
  
  - name: pyhton-pip 
    apt: name=python-pip state=present

  - name: update repo
    apt: update_cache=yes
       
  - name: update repo
    apt: update_cache=yes
 
 