--- 
- name: install jenkins 
  hosts: hosts 
  remote_user: vagrant 
  become: yes 
  tasks: 

  - name: pull jenkins contaitner 
    docker_container: 
      name: jenkinscontainer 
      image: jenkins/jenkins 
      ports:
       - 5789:8080