# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

		 config.vm.define "mahmoud" do |mahmoud|

		 mahmoud.vm.hostname = "mahmoud"
		 mahmoud.vm.box = "chad-thompson-VAGRANTSLASH-ubuntu-trusty64-gui"
		 mahmoud.vm.network :public_network, ip: "192.168.1.116"
		 mahmoud.vm.synced_folder "shared", "/shared"
		 mahmoud.vm.provision :shell, path: "ansible.sh"
		
		 mahmoud.vm.provider :virtual do |master|
			 master.gui = true
			 master.name = "mahmoud"
			 master.memory = 4096
		 master.cpus = 2
		
		 end
			end
			end
Vagrant.configure(2) do |config|
	config.vm.define "newmachine" do |newmachine|

		newmachine.vm.hostname = "node"
		newmachine.vm.box = "chad-thompson-VAGRANTSLASH-ubuntu-trusty64-gui"
		newmachine.vm.network :public_network, ip: "192.168.1.216"
		newmachine.vm.synced_folder "shared", "/shared"
		
		newmachine.vm.provider :virtual do |master|
			master.gui = true
			master.name = "newmachine"
			master.memory = 4096
			master.cpus = 2
		
		
end
	end
end
